### ISSUE TITLE
Opening the Traitor / Detective Menu doesn't work

### ISSUE THREAD

**Issue by alexh2** [Malivil/TTT-Custom-Roles-Outdated#51]
When I open either the Traitor or Detective menu this error is logged.

```[Custom Roles for TTT] gamemodes/terrortown/gamemode/cl_equip.lua:467: attempt to index a nil value
  1. unknown - gamemodes/terrortown/gamemode/cl_equip.lua:467
   2. unknown - lua/includes/modules/concommand.lua:54
```

The menus do work for all the custom roles.

**Comment by Malivil** [comment]
This is caused by a conflict with other addons like the Time Manipulator.

Angela from the Lonely Yogs Discord provided a fix so I will be applying that shortly.

>         if ic.slot ~= nil then
>             if ic.slot > 9 then
>                 ErrorNoHalt("Weapon (" .. SafeTranslate(item.name) .. ") with bad slot value (" .. ic.slot .. ") has been clamped to slot 9 for the traitor menu")
>                 ic.slot = 9
>             elseif ic.slot < 1 then
>                 ErrorNoHalt("Weapon (" .. SafeTranslate(item.name) .. ") with bad slot value (" .. ic.slot .. ") has been clamped to slot 1 for the traitor menu")
>                 ic.slot = 1
>             end
>         end

**Comment by Malivil** [comment]
This is now fixed on the workshop
